# -*- coding: utf-8 -*-
"""Pandai_Encrypt_System.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-X3y3xjJ79SnVrLQCsCRzSxXXrU9J9G7
"""

!pip install gradio pycryptodome qrcode pillow cryptography

import gradio as gr
from Crypto.Cipher import AES
from Crypto.PublicKey import RSA
from Crypto.Cipher import PKCS1_OAEP
from Crypto.Random import get_random_bytes
import base64
import os
import qrcode


# MANAJEMEN KUNCI PERSISTEN (Sistem Produksi)
# Kunci disimpan ke file lokal agar tidak hilang saat aplikasi di-restart
PRIVATE_KEY_FILE = "private_key.pem"
PUBLIC_KEY_FILE = "public_key.pem"

if not os.path.exists(PRIVATE_KEY_FILE) or not os.path.exists(PUBLIC_KEY_FILE):
    # Jika kunci belum ada, generate sepasang kunci baru (RSA 2048-bit)
    key_pair = RSA.generate(2048)
    with open(PRIVATE_KEY_FILE, "wb") as f:
        f.write(key_pair.export_key())
    with open(PUBLIC_KEY_FILE, "wb") as f:
        f.write(key_pair.publickey().export_key())

# Load kunci dari file untuk digunakan di seluruh sesi aplikasi
with open(PRIVATE_KEY_FILE, "rb") as f:
    PRIVATE_KEY_PEM = f.read()
with open(PUBLIC_KEY_FILE, "rb") as f:
    PUBLIC_KEY_PEM = f.read()



# ENGINE KRIPTOGRAFI HYBRID (AES-GCM + RSA)
def encrypt_text(text):
    if not text.strip():
        raise gr.Error("Silakan masukkan teks yang ingin dienkripsi!")
    try:
        data_bytes = text.encode('utf-8')

        # 1. Bangkitkan Session Key AES 256-bit secara acak
        aes_key = get_random_bytes(32)

        # 2. Enkripsi teks dengan AES-GCM (Aman & Otomatis tanpa padding)
        cipher_aes = AES.new(aes_key, AES.MODE_GCM)
        ciphertext, tag = cipher_aes.encrypt_and_digest(data_bytes)

        # 3. Proteksi Kunci AES menggunakan RSA Public Key
        rsa_public_key = RSA.import_key(PUBLIC_KEY_PEM)
        cipher_rsa = PKCS1_OAEP.new(rsa_public_key)
        encrypted_aes_key = cipher_rsa.encrypt(aes_key)

        # 4. Susun Payload format biner (Panjang Kunci + Kunci Terenkripsi + Nonce + Tag + Ciphertext)
        payload = (
            len(encrypted_aes_key).to_bytes(4, 'big') + encrypted_aes_key +
            cipher_aes.nonce +
            tag +
            ciphertext
        )

        return base64.b64encode(payload).decode('utf-8')
    except Exception as e:
        raise gr.Error(f"Terjadi kesalahan enkripsi teks: {str(e)}")


def decrypt_text(text_base64):
    if not text_base64.strip():
        raise gr.Error("Silakan masukkan ciphertext yang ingin didekripsi!")
    try:
        # Decode string Base64 kembali ke biner payload
        raw_payload = base64.b64decode(text_base64.encode('utf-8'))

        # Parsing data payload berdasarkan ukuran panjang bitnya
        aes_len = int.from_bytes(raw_payload[:4], 'big')
        encrypted_aes_key = raw_payload[4:4+aes_len]

        idx = 4 + aes_len
        nonce = raw_payload[idx:idx+16]
        tag = raw_payload[idx+16:idx+32]
        ciphertext = raw_payload[idx+32:]

        # 1. Dekripsi Kunci AES menggunakan RSA Private Key
        rsa_private_key = RSA.import_key(PRIVATE_KEY_PEM)
        cipher_rsa = PKCS1_OAEP.new(rsa_private_key)
        aes_key = cipher_rsa.decrypt(encrypted_aes_key)

        # 2. Dekripsi & Verifikasi Keutuhan Data (Integrity) dengan AES-GCM
        cipher_aes = AES.new(aes_key, AES.MODE_GCM, nonce=nonce)
        decrypted_bytes = cipher_aes.decrypt_and_verify(ciphertext, tag)

        return decrypted_bytes.decode('utf-8')
    except Exception as e:
        # Pesan error yang informatif dan aman untuk user interface
        raise gr.Error("Gagal melakukan dekripsi. Ciphertext rusak, dimodifikasi, atau kunci tidak cocok!")


def encrypt_file(file):
    if file is None:
        raise gr.Error("Silakan pilih file terlebih dahulu!")
    try:
        with open(file.name, "rb") as f:
            data_bytes = f.read()

        output_file = "encrypted_" + os.path.basename(file.name)

        # 1. Bangkitkan Session Key AES 256-bit
        aes_key = get_random_bytes(32)

        # 2. Enkripsi Berkas dengan AES-GCM
        cipher_aes = AES.new(aes_key, AES.MODE_GCM)
        ciphertext, tag = cipher_aes.encrypt_and_digest(data_bytes)

        # 3. Enkripsi Kunci AES dengan RSA Public Key
        rsa_public_key = RSA.import_key(PUBLIC_KEY_PEM)
        cipher_rsa = PKCS1_OAEP.new(rsa_public_key)
        encrypted_aes_key = cipher_rsa.encrypt(aes_key)

        # 4. Gabungkan struktur data menjadi berkas terenkripsi utuh
        payload = (
            len(encrypted_aes_key).to_bytes(4, 'big') + encrypted_aes_key +
            cipher_aes.nonce +
            tag +
            ciphertext
        )

        with open(output_file, "wb") as f:
            f.write(payload)

        return output_file
    except Exception as e:
        raise gr.Error(f"Gagal mengenkripsi file: {str(e)}")


def decrypt_file(file):
    if file is None:
        raise gr.Error("Silakan pilih file terenkripsi terlebih dahulu!")
    try:
        with open(file.name, "rb") as f:
            raw_payload = f.read()

        output_file = "decrypted_" + os.path.basename(file.name)

        # Parsing file payload
        aes_len = int.from_bytes(raw_payload[:4], 'big')
        encrypted_aes_key = raw_payload[4:4+aes_len]

        idx = 4 + aes_len
        nonce = raw_payload[idx:idx+16]
        tag = raw_payload[idx+16:idx+32]
        ciphertext = raw_payload[idx+32:]

        # 1. Ambil Kunci AES lewat RSA Private Key
        rsa_private_key = RSA.import_key(PRIVATE_KEY_PEM)
        cipher_rsa = PKCS1_OAEP.new(rsa_private_key)
        aes_key = cipher_rsa.decrypt(encrypted_aes_key)

        # 2. Dekripsi berkas dan validasi keaslian (GCM Integrity Check)
        cipher_aes = AES.new(aes_key, AES.MODE_GCM, nonce=nonce)
        decrypted_bytes = cipher_aes.decrypt_and_verify(ciphertext, tag)

        with open(output_file, "wb") as f:
            f.write(decrypted_bytes)

        return output_file
    except Exception as e:
        raise gr.Error("Gagal mendekripsi file. File korup atau kunci privat Anda tidak valid!")


def generate_qr(text):
    if not text.strip():
        raise gr.Error("Silakan masukkan teks hasil enkripsi terlebih dahulu!")

    # Validasi Panjang Karakter (Mencegah Crash akibat limitasi kapasitas QR Code)
    if len(text) > 2500:
        raise gr.Error(f"Ciphertext terlalu panjang ({len(text)} karakter). Batas maksimal QR Code aman adalah 2500 karakter!")

    try:
        qr = qrcode.QRCode(version=None, error_correction=qrcode.constants.ERROR_CORRECT_L, box_size=10, border=4)
        qr.add_data(text)
        qr.make(fit=True)
        img = qr.make_image(fill_color="black", back_color="white")
        path = "qrcode.png"
        img.save(path)
        return path
    except Exception as e:
        raise gr.Error(f"Gagal memproses QR Code: {str(e)}")


# UI CSS (DESAIN TAMPILAN GRADIO)
custom_css = """
body { background-color: #f8fafc; font-family: 'Inter', system-ui, -apple-system, sans-serif; color: #1e293b; }
.gradio-container { max-width: 800px !important; margin: 60px auto !important; padding: 0 20px; }

.header-title { text-align: center; color: #0f172a; font-weight: 700; letter-spacing: -0.025em; font-size: 28px; margin-bottom: 4px; }
.subtitle { text-align: center; color: #64748b; font-size: 15px; margin-bottom: 40px; font-weight: 400; }

.tabs { background: #ffffff !important; border: 1px solid #e2e8f0 !important; border-radius: 12px !important; box-shadow: 0 1px 3px 0 rgba(0, 0, 0, 0.05); padding: 24px; }
.tab-nav { border-bottom: 1px solid #e2e8f0 !important; margin-bottom: 24px; display: flex; gap: 8px; }
.tab-nav button { font-weight: 500 !important; color: #64748b !important; padding: 10px 16px !important; border-radius: 6px !important; border: none !important; background: transparent !important; font-size: 14px; transition: all 0.2s; }
.tab-nav button:hover { background: #f1f5f9 !important; color: #0f172a !important; }
.tab-nav button.selected { background: #f1f5f9 !important; color: #0f172a !important; font-weight: 600 !important; }

.section-title { color: #334155; font-size: 16px; font-weight: 600; margin-bottom: 20px; border-left: 3px solid #3b82f6; padding-left: 8px; }

fieldset { border: 1px solid #e2e8f0 !important; background: #ffffff !important; border-radius: 8px !important; }
.dark, .textbox, .file { border-color: #e2e8f0 !important; }

.primary-btn { background: #0f172a !important; color: #ffffff !important; border: none !important; border-radius: 6px !important; font-weight: 500 !important; font-size: 14px !important; padding: 12px 24px !important; transition: background 0.2s; cursor: pointer; width: 100%; }
.primary-btn:hover { background: #1e293b !important; }
.secondary-btn { background: #f1f5f9 !important; color: #334155 !important; border: 1px solid #e2e8f0 !important; border-radius: 6px !important; font-weight: 500 !important; font-size: 14px !important; padding: 12px 24px !important; transition: all 0.2s; cursor: pointer; width: 100%; }
.secondary-btn:hover { background: #e2e8f0 !important; color: #0f172a !important; }

.footer-text { text-align: center; color: #94a3b8; font-size: 12px; margin-top: 40px; }
"""

with gr.Blocks(theme=gr.themes.Default(primary_hue="slate", font=["Inter", "sans-serif"]), css=custom_css) as demo:

    gr.HTML("<h1 class='header-title'>Pandai Encrypt System</h1>")
    gr.HTML("<p class='subtitle'>Automated Hybrid Cryptography — Secure AES-GCM & RSA Implementation</p>")

    with gr.Tabs(elem_classes="tabs"):

        # TAB 1: TEXT CIPHER
        with gr.Tab("Text Cipher"):
            gr.HTML("<h3 class='section-title'>Kriptografi Teks Otomatis</h3>")

            input_text = gr.Textbox(label="Teks Sumber (Input)", lines=4, placeholder="Ketik teks asli untuk enkripsi, atau tempel kode biner base64 untuk dekripsi...")

            with gr.Row():
                encrypt_text_btn = gr.Button("Enkripsi Teks", elem_classes="primary-btn")
                decrypt_text_btn = gr.Button("Dekripsi Teks", elem_classes="secondary-btn")

            result_text = gr.Textbox(label="Hasil Proses (Output)", lines=4, show_copy_button=True, placeholder="Output hasil enkripsi atau dekripsi akan muncul di sini setelah tombol ditekan...")

            encrypt_text_btn.click(encrypt_text, inputs=[input_text], outputs=result_text)
            decrypt_text_btn.click(decrypt_text, inputs=[input_text], outputs=result_text)

        # TAB 2: FILE VAULT
        with gr.Tab("File Vault"):
            gr.HTML("<h3 class='section-title'>Proteksi Berkas Dokumen</h3>")

            with gr.Row():
                with gr.Column():
                    file_input = gr.File(label="Pilih File")
                    with gr.Row():
                        encrypt_file_btn = gr.Button("Encrypt File", elem_classes="primary-btn")
                        decrypt_file_btn = gr.Button("Decrypt File", elem_classes="secondary-btn")

                with gr.Column():
                    file_output_enc = gr.File(label="Unduh Berkas Terenkripsi")
                    file_output_dec = gr.File(label="Unduh Berkas Terdekripsi")

            encrypt_file_btn.click(encrypt_file, inputs=[file_input], outputs=file_output_enc)
            decrypt_file_btn.click(decrypt_file, inputs=[file_input], outputs=file_output_dec)

        # TAB 3: QR CODE
        with gr.Tab("QR Generator"):
            gr.HTML("<h3 class='section-title'>Konversi Ciphertext ke QR Code</h3>")

            with gr.Row():
                with gr.Column():
                    qr_text = gr.Textbox(label="Data Teks Hasil Enkripsi", lines=4, placeholder="Tempel kode teks biner hasil enkripsi di sini...")
                    qr_btn = gr.Button("Generate QR Code", elem_classes="primary-btn")
                with gr.Column(scale=0.6):
                    qr_image = gr.Image(label="Output Grafis QR", type="filepath")

            qr_btn.click(generate_qr, inputs=qr_text, outputs=qr_image)

    gr.HTML("<p class='footer-text'>Pandai Encrypt System v3.3 • Projek Kriptografi Hybrid Persisten</p>")

if __name__ == "__main__":
    demo.launch(share=False)
